"""Storage interface (DI seam) for rule state and incident history."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from gaa.domain.models import Incident, RuleState


@runtime_checkable
class StateStore(Protocol):
    async def get_state(self, rule_name: str) -> RuleState | None: ...

    async def put_state(self, state: RuleState) -> None: ...

    async def list_states(self) -> tuple[RuleState, ...]: ...

    async def record_incident(self, incident: Incident, screenshot: bytes | None = None) -> int: ...

    async def resolve_incident(self, incident_id: int, resolved_at: float) -> None: ...

    async def list_incidents(self, limit: int = 50) -> tuple[Incident, ...]: ...

    async def get_incident(self, incident_id: int) -> Incident | None: ...

    async def get_screenshot(self, incident_id: int) -> bytes | None: ...

    async def count_recent(self, rule_name: str, since: float) -> int: ...

    async def open_incident_id(self, rule_name: str) -> int | None: ...

    async def set_incident_thread(self, incident_id: int, thread_id: str) -> None: ...

    async def get_incident_by_thread(self, thread_id: str) -> Incident | None: ...
